[package]
name = "s_nor"
version = "1.0.1"
edition = "2021"
authors = ["Skub" , "Neko"]
description = "A Very Simple To Use Encryption Algorithm * Not Ment For Professional Use"
license = "MIT"

[dependencies]
clearscreen = "3.0.0"
colored = "2.1.0"
