[package]
name = "nor"
version = "1.0.0"
edition = "2021"
authors = ["Skub"]
description = "A Very Simple To Use Encryption Algorithm * Not Ment For Professional Use"
license = "MIT"

[dependencies]
clearscreen = "3.0.0"
colored = "2.1.0"
